language: cpp
os: linux
dist: xenial
sudo: required

compiler:
- gcc

branches:
  only:
  - master
  - temp_sense
  - travisci

env:
  global:
  - LC_NUMERIC=en_us.UTF8

before_install:
- echo $(uname -a)

# install required packages
#install:
- sudo apt-get install build-essential --install-suggests
- sudo apt-get install docbook-utils
- sudo apt-get install libreadline-dev
- sudo apt-get install zlib1g:i386
- sudo apt-get install 
- sudo apt-get install linux-headers-$(uname -r)
- sudo apt-get install sdcc fxload
- sudo apt-get install autotools-dev
- sudo apt-get install automake
- sudo apt-get install libtool
- sudo apt-get install libglibmm-2.4
- sudo apt-get install libglib2.0
- sudo apt-get install xsltproc

# clone bel_projects and check out the master branch
# update submodules
# hack Makefile to fix make failure regarding spec_wb.o
# check out the current branch of saftlib
# make and install etherbone etc
before_script:
- echo $TRAVIS_BRANCH
- echo $TRAVIS_PULL_REQUEST_BRANCH
- echo $TRAVIS_REPO_SLUG
- echo $TRAVIS_PULL_REQUEST_SLUG
- echo $TRAVIS_PULL_REQUEST
- git clone --recursive https://github.com/ebold/bel_projects.git
- cd bel_projects
- git checkout master
- ./fix-git.sh
- sed -i 's/spec_wb.o//g' ip_cores/fpga-config-space/pcie-wb/Makefile
- cd ip_cores/saftlib
- if [ $TRAVIS_PULL_REQUEST -ne 0 ]; then git checkout $TRAVIS_PULL_REQUEST_BRANCH; else git checkout $TRAVIS_BRANCH; fi
- cd ../..
- make etherbone
- make tools
- make driver
- sudo make install

# make and install saftlib
script:
- make saftlib
- sudo make saftlib-install
